agents:
  healthcare-basic:
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 71dvaqhfvo1srna6sd8e55onjl
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_bo5fvclJc/.well-known/openid-configuration
    aws:
      account: '345667997821'
      ecr_auto_create: false
      ecr_repository: 345667997821.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-healthcare-basic
      execution_role: arn:aws:iam::345667997821:role/HealthcareStackInfra-RuntimeAgentCoreRole-V396McTDSliH
      execution_role_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      observability:
        enabled: true
      protocol_configuration:
        server_protocol: HTTP
      region: us-east-1
    bedrock_agentcore:
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:345667997821:runtime/healthcare-basic-AGENT_ID
      agent_id: healthcare-basic-AGENT_ID
      agent_session_id: null
    codebuild:
      execution_role: arn:aws:iam::345667997821:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1
      project_name: bedrock-agentcore-healthcare-basic-builder
      source_bucket: bedrock-agentcore-codebuild-sources-345667997821-us-east-1
    container_runtime: finch
    entrypoint: main.py
    name: healthcare-basic
    oauth_configuration: null
    platform: linux/arm64
  healthcare-premium:
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 71dvaqhfvo1srna6sd8e55onjl
        discoveryUrl: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_bo5fvclJc/.well-known/openid-configuration
    aws:
      account: '345667997821'
      ecr_auto_create: false
      ecr_repository: 345667997821.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-healthcare-premium
      execution_role: arn:aws:iam::345667997821:role/HealthcareStackInfra-RuntimeAgentCoreRole-V396McTDSliH
      execution_role_auto_create: true
      network_configuration:
        network_mode: PUBLIC
      observability:
        enabled: true
      protocol_configuration:
        server_protocol: HTTP
      region: us-east-1
    bedrock_agentcore:
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:345667997821:runtime/healthcare-premium-AGENT_ID
      agent_id: healthcare-premium-AGENT_ID
      agent_session_id: null
    codebuild:
      execution_role: arn:aws:iam::345667997821:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1
      project_name: bedrock-agentcore-healthcare-premium-builder
      source_bucket: bedrock-agentcore-codebuild-sources-345667997821-us-east-1
    container_runtime: finch
    entrypoint: main_premium.py
    name: healthcare-premium
    oauth_configuration: null
    platform: linux/arm64
default_agent: healthcare-basic
